name: Test
on:
  pull_request:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check syntax
    strategy:
      matrix:
        node_version: ["18"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: npm install
    - name: Check sources
      run: npm run check
  test:
    name: "${{ matrix.os }}, node ${{ matrix.node_version }}"
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: ["16", "18", "19"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: npm install
    - name: Test sources
      run: npm run test:ci
